fix: arrayble is unusable
sindresorhus/type-fest pull request #1003
Opened 2024-12-10 09:17 UTC by adduserwyw

fix: #952

2024-12-10 09:22 UTC, Emiyaaaaa requested changes

2024-12-10 09:22 UTC, Emiyaaaaa commented on source/arrayable.d.ts
> + */
```suggestion
*/
```

2024-12-10 10:13 UTC, adduserwyw commented on source/arrayable.d.ts
> + */
> 

Fixed!

2024-12-11 13:49 UTC, sindresorhus commented on source/arrayable.d.ts
> +export type Arrayable<T> = T | T[];
Add a TODO comment that links to the TS issue, so we someday can add back `readonly`.

2024-12-12 03:18 UTC, Emiyaaaaa approved these changes

2024-12-12 18:35 UTC, merged