Add `SetNonNullable` type
sindresorhus/type-fest pull request #199
Opened 2021-04-16 07:39 UTC by Smtih

Often, you will want to extract code the checks or asserts that specific fields of an object are present, this makes typing this much easier.

```typescript
function assertHasName(person: Person): asserts person is SetNonNullable<Person, "name"> {
  if(person.name == null) throw new Error("Person has no name");
}
```

2021-04-16 08:20 UTC, sindresorhus commented
> I wonder if we could just overwrite the built-in NonNullable version with a more powerful one that also accepts which keys to apply to, as discussed in #171.

Any thoughts on this?

2021-04-16 09:39 UTC, Smtih commented
While we could do this, I'm unsure what the benefit is.

I think it would be pretty unexpected for a type named non-nullable to do this, especially as it's already a built in type Does it also make the entire object non-nullable as well as the keys?

I think having the word 'Set' makes it clear how this type operates.

2021-04-18 16:28 UTC, sindresorhus requested changes

2021-04-18 16:28 UTC, sindresorhus commented on source/set-non-nullable.d.ts
> +
Can you mention how it related to `SetRequired` and the inverse in the `SetRequired` doc comment?

2021-04-18 16:28 UTC, sindresorhus commented on source/set-non-nullable.d.ts
> +Create a type removes nullish (optional, undefined and null) types from the given keys. The remaining keys are kept as is.
```suggestion
Create a type that removes nullish (optional, `undefined`, and `null`) types from the given keys. The remaining keys are kept as is.
```

2021-04-18 16:28 UTC, sindresorhus commented
Please follow: https://github.com/sindresorhus/type-fest/blob/main/.github/contributing.md

2021-04-18 16:28 UTC, sindresorhus commented
Alright, let's go with `Set` like you have it.

2021-06-03 20:26 UTC, sindresorhus commented
Friendly bump :)

2021-07-08 11:52 UTC, sindresorhus commented
https://github.com/sindresorhus/type-fest/issues/228

2021-07-08 11:52 UTC, closed without merging