Add `SetNonNullable` type
sindresorhus/type-fest pull request #245
Opened 2021-08-06 01:15 UTC by Smtih

Adds `SetNonNullable<Type, Keys>` which allows someone to remove nullish values at specific keys of an object. This is useful when defining type guards.

```ts
type Person {
	firstName?: string | null;
	lastName?: string | null;
}

function hasFirstName(person: Person) person is SetNonNullable<Person, "firstName"> {
	return person.firstName != null;
}
```

Continuation of https://github.com/sindresorhus/type-fest/pull/199
Addresses https://github.com/sindresorhus/type-fest/issues/228

If anything is still missing let me know, I've tried to fulfil the contributing guidelines.

2021-09-04 11:25 UTC, BendingBender requested changes
Other than the suggested changes this looks good to me. I have just one principled question: Wouldn't it make more sense to make this type have only one responsibility, just like `SetRequired`? I mean that this type should only remove the `null`/`undefined` from the object values but don't touch the optionality of the keys? This could make a difference especially in the context of the newly introduced [`--exactOptionalPropertyTypes` compiler option](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#exact-optional-property-types). When designed like this, users could mix and match `SetNonNullable`/`SetRequired` as they see fit and we could even introduce a combined type that makes both transformations. @sindresorhus

2021-09-04 11:25 UTC, BendingBender commented on source/set-non-nullable.d.ts
> +This behaves in a similar manor to `SetRequired<T,K>` by removing optionals, however also applies the `NonNullable<T>` operator to the values at the specified keys.
```suggestion
Create a type that removes nullish (optional, `undefined` and `null`) types from the given keys. The remaining keys are kept as is.
This behaves in a similar manner to `SetRequired<T,K>` by removing optionals, however also applies the `NonNullable<T>` operator to the values at the specified keys.
```

2021-09-04 11:25 UTC, BendingBender commented on source/set-non-nullable.d.ts
> +// 	a?: number;
```suggestion
// 	a?: number; // Kept as is, was not mentioned in `'b' | 'c' | 'd' | 'e'` type argument.
```

2021-09-05 10:42 UTC, sindresorhus commented
I agree with @BendingBender. The name is also misleading as it contains `NonNullable` in the name, but it does even more than `NonNullable`.

2021-09-05 22:49 UTC, sindresorhus commented
@Smtih If you have time, it would be great if you could help review some of the other open pull requests. 🙏

2021-09-06 02:41 UTC, goodoldneon commented
+1 to the name concerns. Maybe `SetNonNullish` instead?

2021-09-06 03:03 UTC, goodoldneon commented on source/set-non-nullable.d.ts
> +type Person {
Missing `=`

2021-09-06 03:03 UTC, goodoldneon commented on source/set-non-nullable.d.ts
> +function hasFirstName(person: Person) person is SetNonNullable<Person, "firstName"> {
```suggestion
function hasFirstName(person: Person): person is SetNonNullable<Person, "firstName"> {
```

2021-09-06 11:01 UTC, sindresorhus commented
> Maybe SetNonNullish instead?

I don't think the distinction between "nullable" and "nullish" are clear enough.

2021-09-06 12:00 UTC, goodoldneon commented
> I don't think the distinction between "nullable" and "nullish" are clear enough.

“Nullish” is the official term for “either `null` or `undefined`“. For example:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

2021-09-06 13:58 UTC, sindresorhus commented
@goodoldneon Yes, but TS uses "nullable" for null/undefined in `NonNullable`. So it just makes it slightly different without actually making it any clearer that it also deals with optionality.

2021-09-06 14:44 UTC, goodoldneon commented
@sindresorhus good point. It seems like the JavaScript community considers a "nullable" to be a something that can accept either `null` or `undefined`. It's unfortunate that `null` and `undefined` are conflated like that, but it is what it is.

If the goal of the proposed type is to apply the standard library `NonNullable` type over specific keys, then I think `SetNonNullable` is the most intuitive option

2022-01-08 07:15 UTC, sindresorhus commented
@Smtih Still interested in finishing this?

2022-03-22 10:23 UTC, closed without merging