Add test that ensure all files in source directory use .d.ts extension
sindresorhus/type-fest pull request #264
Opened 2021-09-13 10:07 UTC by wafuwafu13

https://github.com/sindresorhus/type-fest/issues/261

2021-09-13 14:00 UTC, sindresorhus requested changes

2021-09-14 09:01 UTC, wafuwafu13 commented
Thank you for reviewing!
I will be deleting these files after receive your review.
https://github.com/wafuwafu13/type-fest/commit/c0358a821ac7298747a2ca23347543c89be0fdc7

2021-09-17 03:39 UTC, sindresorhus commented on script/test/source-files-extension.js
> +		let hasWrongExtensionFile = false;
```suggestion
		let hasIncorrectFileExtension = false;
```

2021-09-17 10:14 UTC, sindresorhus commented
Make sure you run `$ npm test` locally before pushing ;)

2021-09-17 10:19 UTC, wafuwafu13 commented
Done :sweat_drops:

2021-09-17 10:25 UTC, merged

2021-09-17 10:25 UTC, sindresorhus commented
Thanks for contributing this :)