Add `RemoveIndex` type
sindresorhus/type-fest pull request #335
Opened 2021-12-06 03:53 UTC by buschtoens

`RemoveIndex<ObjectType>` removes any index signatures from a given `ObjectType`, so that only explicitly defined properties remain.

This type was taken from this [StackOverflow answer](https://stackoverflow.com/a/68261113/420747) by @gerrit0.

#### Use-cases

- Remove overly permissive signatures from third-party types.

#### Example

[Playground Link](https://www.typescriptlang.org/play?ts=4.4.4#code/JYOwLgpgTgZghgYwgAgKIA84FsAOAbCASXGniWQG8AoASAHo7kAVACwgGcVQATCdZdsADmIOGACuUDsgDuwPHmQAjFFKwB7AG4RuAOloBtdAC4BYKKCEBdU3BABPANyGTyEOKwqoN5HadVaBmQAZXtPdUU7bmRIXDwxFHZzS2QcMUgoEGQePgFhUQkpdl8pZHUQPHtfTTh5OCUCQMYkuCgwFLkwFmZ7HAhghAscMGQAFl1xpuQWMDAcdmMGXk0G9SF2XSxgQfV2dRgwXQR1LDowXo5B4GG6OxB1cRAESwBac772K+GX0Z+XlTAcDoAGJ2GElBE3hA4gkXoIRGJJBwXKYweE8D4-M4aEZTAADNhwbgvAAkFCSFhAQgAvnifBTLNjccg8WSGVTqW9ang6ajklSma4CRAiaTyfyaVz5LyzJShIL8WSlMJQGBafSJQqWdCVNxeMSye5PNB1Xy5c4pqwOCg+PhtsAwJVkLwYKAdMgANYQezFOQKZBqWogfQ0GDqdSmADkSlakexAEdxOgAPxRmMALzjVGpAXeKAAStCtEQQLx0AAeADySgAVhAEGAmBcAHzIAC8lEMAGlvU2+tksl77PtkNW6w2+yg4MUKNTkHxIKXioXjlBuOWe-ZJwAaZCPD33GQgZu0GjJtwQbRQU+mTeTnxj+uNi4GO8XKzOakWvPIQvscR4CMHaFho2jEGW5YYNg+AlhkZAQM2zhBG2rYUMgYYRsg0axo4yCJimaZwJmyAAD57qWECuiAOi4dSQA)

```ts
import {RemoveIndex} from 'type-fest';

interface Example {
  // These index signatures will be removed.
  [x: string]: any
  [x: number]: any
  [x: symbol]: any
  [x: `head-${string}`]: string
  [x: `${string}-tail`]: string
  [x: `head-${string}-tail`]: string
  [x: `${bigint}`]: string
  [x: `embedded-${number}`]: string

  // These explicitly defined keys will remain.
  foo: 'bar';
  qux?: 'baz';
}

type ExampleWithoutIndexSignatures = RemoveIndex<Example>;
// => { foo: 'bar'; qux?: 'baz' | undefined; }
```

2021-12-06 04:09 UTC, buschtoens commented
I wasn't too sure what to name this type and am happy to change the name, if you think there's something better. Before settling on `RemoveIndex`, I considered these alternatives:

- `KnownKeys` / `OnlyKnownKeys`
  - Confusing, as it may imply that the result is a sub-type of `keyof ObjectType` instead of a sub-type of `ObjectType`.
- `...IndexSignature`
  - More verbose than just `...Index`.
- `...Signature`
  - Not specific enough. Could e.g. refer to a function signature.
- `Without...` / `Drop...` / `Exclude...` / `Ignore...` / `Filter...` / `No...`
  - Some of these already have a different meaning attached to them.
  - The imperative `Remove...` form aligns well with existing types like `SetRequired` & `SetOptional`.

2022-01-06 13:07 UTC, sindresorhus commented
I would name it `RemoveIndexSignature`. `RemoveIndex` can be ambiguous.

2022-01-06 13:09 UTC, sindresorhus requested changes

2022-01-06 13:09 UTC, sindresorhus commented on readme.md
> +  explicitly defined properties, absent of any index signatures.
Don't hard-wrap.

2022-01-08 04:55 UTC, sindresorhus commented
> Please help review the other open pull requests. If there are no open pull requests, provide some feedback on some of the open issues. - https://github.com/sindresorhus/type-fest/blob/main/.github/contributing.md

2022-01-19 11:48 UTC, buschtoens commented
I've addressed your review comments. Thank you!

2022-01-20 06:42 UTC, merged

2023-12-04 01:50 UTC, allejo commented
If anyone stumbles upon this PR like I did, this was renamed to `OmitIndexSignature` as of [v4.0.0](https://github.com/sindresorhus/type-fest/releases?q=RemoveIndexSignature&expanded=true).