Add `TransformDeep` type
sindresorhus/type-fest pull request #354
Opened 2022-01-19 15:23 UTC by JuanM04

## `TransformDeep<Base, Value>`

Create a deeply transformed version of another type where each value (`BuiltIns` or functions) are replaced by an arbitrary type.

```ts
import {TransformDeep} from 'type-fest';

type Example = TransformDeep<{
  foo: number
  bar: { qux: boolean }
}, string>;

// => { foo: string; bar: { qux: string } }
```

### Use case

When validating an object, return an object with the same key disposition where each value is a string with a description of the error.

```ts
import {PartialDeep, TransformDeep} from 'type-fest';
const formValues: Values = {
  name: "John Doe",
  address: {
    street: "Av. de Mayo",
    number: 505,
    city: "Buenos Aires",
    country: "Argentina"
  }
  subscribeToNewsletter: true
};

const validate = (values: Values): PartialDeep<TransformDeep<Values, string>> => {
  // ...
}

const errors = validate(formValues);
// => 
// { 
//   name?: string
//   address?: {
//     street?: string
//     number?: string
//     city?: string
//     country?: string
//   }
//   subscribeToNewsletter?: string
// }
```

2022-01-22 05:56 UTC, sindresorhus requested changes

2022-01-22 05:56 UTC, sindresorhus commented on source/transform-deep.d.ts
> +type IsAny<T> = 0 extends 1 & T ? true : false; // https://stackoverflow.com/a/49928360/3406963
This should be moved to the `internal` file.

2022-01-22 05:56 UTC, sindresorhus commented on source/transform-deep.d.ts
> +	name: "John Doe",
Use single-quotes.

2022-01-22 05:58 UTC, sindresorhus commented
I'm not sure about this one. It seems a bit niche. It seems like a type that should be part of the validation library you're using. I cannot think of any other use-case for this type than what you have presented.

---

// @papb @younho9

2022-01-22 07:46 UTC, younho9 commented
> It seems like a type that should be part of the validation library you're using. I cannot think of any other use-case for this type than what you have presented.

I'm with @sindresorhus on this one.

2022-01-22 17:17 UTC, JuanM04 commented
> I'm not sure about this one. It seems a bit niche. It seems like a type that should be part of the validation library you're using. I cannot think of any other use-case for this type than what you have presented.

That's fair. Do you want me to close this PR?

2022-01-25 10:17 UTC, sindresorhus commented
I think this is very similar to https://github.com/sindresorhus/type-fest/pull/321, which provided some additional use-cases, and is accepted. Would that solve your need? And if yes, would you be able to help review it?

2022-01-25 14:51 UTC, JuanM04 commented
> I think this is very similar to #321

That's basically the same goal. Sorry I didn't notice it

2022-01-25 14:51 UTC, closed without merging

2022-01-27 11:29 UTC, sindresorhus commented
https://github.com/sindresorhus/type-fest/releases/tag/v2.11.0