Add `IfAny` and `IsAny` types
sindresorhus/type-fest pull request #505
Opened 2022-10-25 06:41 UTC by nullndr

## Changelog

This PR adds two new types: `IfAny` and `IsAny`.

### IfAny

Given three types `Cond`, `Then` and `Else` assign `Then` if `Cond` is any, `Else` otherwise.

### IsAny

Returns `true` or `false` indicating if `Cond` is `any`.

## Links

For more info, see [`this stack overflow answer`](https://stackoverflow.com/questions/49927523/disallow-call-with-any/49928360#49928360).

## Notes

I'm drafting this PR because I don't know in what categories these types should be. 
I'm waiting for a response to this doubt.

2022-10-25 06:49 UTC, sindresorhus commented
Seems like useful types.

2022-10-25 06:49 UTC, sindresorhus commented
Please follow: https://github.com/sindresorhus/type-fest/blob/main/.github/contributing.md#submitting-a-new-type

2022-10-25 06:52 UTC, sindresorhus commented
> I'm drafting this PR because I don't know in what categories these types should be.

Just put it in `Utilities` for now.

2022-10-25 06:52 UTC, sindresorhus commented
You also need to add them to the readme.

2022-10-25 06:53 UTC, nullndr commented
> You also need to add them to the readme.

Yes, I was waiting for the category, I'm gonna update this PR in 10 minutes

2022-10-25 07:09 UTC, sindresorhus requested changes

2022-10-25 07:09 UTC, nullndr commented on index.d.ts
> +export type {IsAny} from './source/is-any';
Oh sorry I'm missing these

2022-10-25 07:51 UTC, sindresorhus commented
Try to look over your own diff. There a lots of minor things to improve. Basically, spend some more time perfecting it.

Also make sure you follow everything in https://github.com/sindresorhus/type-fest/blob/main/.github/contributing.md#submitting-a-new-type

2022-10-26 05:45 UTC, nullndr commented
@sindresorhus sorry to bother you but could you tell me what's still missing in your opinion?

2022-10-29 10:37 UTC, sindresorhus commented
https://github.com/sindresorhus/type-fest/pull/505#discussion_r1004070861 is not resolved.

2022-10-29 10:39 UTC, sindresorhus requested changes

2022-10-29 10:39 UTC, sindresorhus commented on index.d.ts
> +export type {TsConfigJson} from './source/tsconfig-json';
Don't make unrelated changes.

2022-10-29 10:39 UTC, sindresorhus commented on test-d/if-any.ts
> +
```suggestion
```

2022-10-29 10:39 UTC, sindresorhus commented on source/is-any.d.ts
> +export type IsAny<Cond> = 0 extends 1 & Cond ? true : false;
I don't think `Cond` is a correct name for this type parameter.

2022-10-29 10:39 UTC, sindresorhus commented on source/is-any.d.ts
> +  }
Use tab-indentation

2022-10-29 10:39 UTC, sindresorhus commented on source/is-any.d.ts
> +  if(should_print) {
Use proper formatting an camel-case.

2022-10-29 10:39 UTC, sindresorhus commented on source/if-any.d.ts
> +Used to create a ternary operator type above the `any` type.
This should be the same as the readme description.

2022-10-29 10:39 UTC, sindresorhus commented on source/if-any.d.ts
> +  c: "hello",
single-quotes

2022-10-29 10:39 UTC, sindresorhus commented on source/is-any.d.ts
> +function execute<T>(data: T, should_print: IsAny<T>) {
It's not clear to the user why `IsAny` is used here.

2022-10-29 10:39 UTC, sindresorhus commented on source/if-any.d.ts
> +type WithoutAnyValues = { [K in keyof WithAnyValues]: IfAny<WithAnyValues[K], number, WithAnyValues[K]>}
It would be better with a realistic real-world example.

2022-11-20 12:08 UTC, sindresorhus requested changes

2022-11-20 12:08 UTC, sindresorhus commented on source/if-any.d.ts
> +Create a ternary operator type checking if the given type if `any`.
Typo: `if`

2022-11-20 12:08 UTC, sindresorhus commented on readme.md
> +- [`IsAny](source/is-any.d.ts) - Create a `true`/`false` type depending if the given type is `any`.
```suggestion
- [`IsAny](source/is-any.d.ts) - Returns a `boolean` for whether the given type is `any`.
```

2022-11-20 12:08 UTC, sindresorhus commented on readme.md
> +- [`IfAny](source/if-any.d.ts) - Create a ternay operator type checking if the given type is `any`.
I think this needs a better description. It's not clear what "ternay operator type checking" means. Also typo.

2022-11-20 12:09 UTC, sindresorhus commented
> Try to look over your own diff. There a lots of minor things to improve. Basically, spend some more time perfecting it.

Still applies.

2022-12-25 23:07 UTC, sindresorhus commented
Bump :)

2023-01-20 08:08 UTC, closed without merging