Add `DeepFlattenRecord` type (and helpers)
sindresorhus/type-fest pull request #571
Opened 2023-03-12 06:53 UTC by dwheale

I know the preference is to submit one type per PR but the other types are required for `DeepFlattenRecord` to work. I found that an API I was pulling from provided data in a nested format, which I needed flattened.

2023-03-13 06:31 UTC, tommy-mitchell commented
What are all the types that have been added? It would probably help to add them to the PR description. Do all of them need to be exposed, or can some be internal / part of `deep-flatten-record.d.ts`?

I think the convention is that `Deep` types have the label added to the suffix, not prefix (i.e. `FlattenRecordDeep`).

2023-03-14 11:31 UTC, sindresorhus requested changes

2023-03-14 11:31 UTC, sindresorhus commented on source/deep-flatten-record.d.ts
> +  objectKey: {
Use tab-indentation.

2023-03-14 11:31 UTC, sindresorhus commented on source/deep-flatten-record.d.ts
> +import type { DeepFlattenRecord } from 'type-fest';
```suggestion
import type {DeepFlattenRecord} from 'type-fest';
```

2023-03-14 11:31 UTC, sindresorhus commented on source/deep-flatten-record.d.ts
> +@param BaseType The type to flatten
```suggestion
@param BaseType - The type to flatten.
```

2023-03-14 11:31 UTC, sindresorhus commented on source/deep-flatten-record.d.ts
> +it's keys will be optional. This can be disabled by setting `cascadeOptionality` in `DeepFlattenOptions` to `false`.
Don't hard-wrap.

2023-03-14 11:31 UTC, sindresorhus commented on source/deep-flatten-record.d.ts
> +	 */
```suggestion
	/**
	Whether to cascade optionality on an object (e.g. if a parent is optional, all children will be as well regardless of their original optionality)

	@default true
	*/
```

2023-05-20 09:13 UTC, sindresorhus commented
Bump

2023-06-14 12:54 UTC, sindresorhus commented
Closing for lack of response: https://github.com/sindresorhus/type-fest/issues/633

2023-06-14 12:54 UTC, closed without merging