Add `LiteralToPrimitiveDeep` Type
sindresorhus/type-fest pull request #584
Opened 2023-03-29 22:30 UTC by alvis

This PR introduces a new utility type called `LiteralToPrimitiveDeep`, which aims to simplify the handling of data from a json file.

For example, if you want to pass a tsconfig to a function expecting a TsConfigJSON type, then you have to either import the expected type and cast the data to it, or simply cast the data to any.

```
/* function.ts */
import type { TsConfigJson } from 'type-fest';

export function doSomethingWithTSConfig(config: LiteralToPrimitiveDeep<TsConfigJson>) { ... }

/* another.ts */
import tsconfig from 'path/to/tsconfig.json';

// no casting is needed to pass the type check
doSomethingWithTSConfig(tsconfig);

// if LiteralToPrimitiveDeep is not used, you need to cast the imported data like this: 
doSomethingWithTSConfig(tsconfig as TsConfigJson);
doSomethingWithTSConfig(tsconfig as any);
 ```

2023-03-30 02:15 UTC, sindresorhus commented on readme.md
> +_Requires TypeScript >=4.7_
Don't make unrelated changes.

2023-03-30 02:16 UTC, sindresorhus commented on source/literal-to-primitive-deep.d.ts
> + *
Follow the existing style with not `*` prefixes.

2023-03-30 02:16 UTC, sindresorhus commented
Thanks for contributing. Make sure you adhere to https://github.com/sindresorhus/type-fest/blob/main/.github/contributing.md

2023-03-31 12:42 UTC, alvis commented
Sorry for missed the code style. They are corrected.

2023-04-02 04:11 UTC, sindresorhus requested changes

2023-04-02 04:11 UTC, sindresorhus commented on readme.md
> +- [`LiteralToPrimitiveDeep`](source/literal-to-primitive-deep.d.ts) - Like `LiteralToPrimitive` except that it converts the literal types deeply.
It only works with object/array, so it should make that clear, so it should maybe make that clear.

2023-04-02 04:11 UTC, sindresorhus commented on source/literal-to-primitive-deep.d.ts
> +Given a constant object, return a new object with the same keys but with all the values converted to primitives.
The first line should be the same as the readme description.

2023-04-02 04:11 UTC, sindresorhus commented on source/literal-to-primitive-deep.d.ts
> +import type { LiteralToPrimitiveDeep, TsConfigJson } from 'type-fest';
```suggestion
import type {LiteralToPrimitiveDeep, TsConfigJson} from 'type-fest';
```

2023-04-02 19:56 UTC, alfiomy commented
تمام

2023-04-02 19:57 UTC, alfiomy approved these changes

2023-04-03 07:14 UTC, alvis commented
@sindresorhus Documentation should be much clearer now :)

2023-04-04 06:53 UTC, merged

2023-04-04 06:53 UTC, sindresorhus commented
Thanks :)