fix(ReadonlyDeep): lessen instantiation excessively deep errors
sindresorhus/type-fest pull request #650
Opened 2023-07-23 21:25 UTC by ethanresnick

This is an attempt to fix #467, which I've also run into repeatedly. It uses a helper type described here https://github.com/kysely-org/kysely/pull/483

2023-07-28 21:35 UTC, ethanresnick commented
@sindresorhus Anything I can do to help move this forward, or more info you need from me? I'm running into these 'instantiation excessively deep' errors quite a lot with `ReadonlyDeep` and would love to see this merged.

2023-07-29 12:24 UTC, sindresorhus requested changes

2023-07-29 12:24 UTC, sindresorhus commented on source/readonly-deep.d.ts
> +type DrainOuterGeneric<T> = [T] extends [unknown] ? T : never;
Move this to internal.d.ts

2023-07-29 12:24 UTC, sindresorhus commented on source/readonly-deep.d.ts
> +avoid "TS2589: Type instantiation is excessively deep and possibly infinite."
Don't hard-wrap.

2023-07-29 12:25 UTC, sindresorhus commented
It would be nice to have some tests that would produce "Type instantiation is excessively deep and possibly infinite" before this change.

2023-07-29 12:26 UTC, sindresorhus commented on source/readonly-deep.d.ts
> +export type ReadonlyDeep<T> = T extends BuiltIns | Opaque<unknown>
The `Opaque` addition could use a short code comment on why it's there.

2023-07-30 20:32 UTC, ethanresnick commented
Hi @sindresorhus! Ok, I've done substantially more debugging here and have updated the PR accordingly. I'll update the OP soon to explain each change. Every change has a test, I believe.

2023-08-04 05:57 UTC, ethanresnick commented
@sindresorhus How does it look now (if you have a chance to look)? Thanks!

2023-08-08 09:46 UTC, merged

2023-08-09 03:23 UTC, ethanresnick commented
Thanks @sindresorhus!

2023-08-09 07:52 UTC, ehoogeveen-medweb commented
By the way, does `WritableDeep` suffer from the same issues or is it unaffected? The implementations were very similar before this change.

2023-08-21 12:34 UTC, sindresorhus commented
https://github.com/sindresorhus/type-fest/issues/664