Add ArrayValues type
sindresorhus/type-fest pull request #720
Opened 2023-10-20 18:44 UTC by lucasteles

Implements part of #670

2023-10-20 21:05 UTC, sindresorhus requested changes

2023-10-20 21:05 UTC, sindresorhus commented on source/array-values.d.ts
> +```
Use the example from ArrayIndices here too.

2023-10-20 21:05 UTC, sindresorhus commented on source/array-values.d.ts
> +export type ArrayValues<Element extends readonly unknown[]> = IterableElement<Element>;
Why not just

```suggestion
export type ArrayValues<T extends readonly unknown[]> = T[number];
```

2023-10-20 22:51 UTC, lucasteles commented
@sindresorhus fixed

2023-10-21 06:30 UTC, sindresorhus commented
Can you fix the merge conflict?

2023-10-21 16:15 UTC, merged