Add SetFieldType Type
sindresorhus/type-fest pull request #721
Opened 2023-10-20 23:09 UTC by lucasteles

implements #718

2023-10-21 06:54 UTC, sindresorhus requested changes

2023-10-21 06:54 UTC, sindresorhus commented on source/set-field-type.d.ts
> +Create a type that changes the given keys types.
```suggestion
Create a type that changes the type of the given keys.
```

readme too

2023-10-21 06:54 UTC, sindresorhus commented on source/set-field-type.d.ts
> +Use-case: You want to change the type of one or more fields of a model.
```suggestion
Use-cases:
- Creating variations of a base model.
- Fixing incorrect external types.
```

2023-10-21 14:56 UTC, Emiyaaaaa commented
https://github.com/sindresorhus/type-fest/issues/718#issuecomment-1773811329
@sindresorhus @lucasteles

2023-10-25 11:55 UTC, sindresorhus requested changes

2023-10-25 11:55 UTC, sindresorhus commented on source/set-field-type.d.ts
> +Create a type that changes the type of the given keys.
This should be the text in the readme.

2023-10-25 11:55 UTC, sindresorhus commented on source/set-field-type.d.ts
> +
Add a tip about using the `Merge` type if you need to change multiple properties to different types.

2023-10-25 11:55 UTC, sindresorhus commented
Tests are failing.

2023-10-25 14:56 UTC, lucasteles commented on source/set-field-type.d.ts
> +Create a type that changes the type of the given keys.
```suggestion
Create a type that changes the given keys types.
```

2023-10-25 16:38 UTC, sindresorhus commented
Sorry if it was not clear with https://github.com/sindresorhus/type-fest/pull/721#discussion_r1371611693. It should be the inverse. Apply that text to the readme too.

2023-10-25 16:44 UTC, merged