Add `Paths` type
sindresorhus/type-fest pull request #741
Opened 2023-11-05 11:11 UTC by Emiyaaaaa

- Close #213 
 - Close #300

2023-11-05 17:13 UTC, sindresorhus commented
It was suggested in the issue that the `Get` type could use this. Do you think so?

2023-11-05 17:22 UTC, sindresorhus requested changes

2023-11-05 17:22 UTC, sindresorhus commented on source/paths.d.ts
> +open('fileName'); // Pass
Show an example with array too.

2023-11-05 17:22 UTC, sindresorhus commented on source/paths.d.ts
> +//=> "fileName" | "folder" | "folder.subfolder" | "folder.subfolder.fileName"
single-quotes

2023-11-05 17:22 UTC, sindresorhus commented on source/paths.d.ts
> +	fileName: string;
```suggestion
	filename: string;
```

2023-11-05 17:22 UTC, sindresorhus commented on readme.md
> +- [`Paths`](source/paths.d.ts) - Generate a union of all the possible paths in given object.
```suggestion
- [`Paths`](source/paths.d.ts) - Generate a union of all possible paths to properties in the given object.
```

2023-11-05 17:22 UTC, sindresorhus commented on source/paths.d.ts
> +
Should mention that it also works for arrays.

2023-11-07 10:58 UTC, Emiyaaaaa commented
> It was suggested in the issue that the `Get` type could use this. Do you think so?

`Get` accept 'string' and 'string[]':
1. argument 'string' is like `hits.hits[0]._source.name`, but `Paths` current result like `hits.hits.0._source.name`
I'm having some trouble:
Is result of `Paths` wrong? 
or should add a option to choose the handling of array? 
or path in `Get` and `Paths` just are not same thing?
3. argument 'string[]' is like `['hits','hits', '0', '_source', 'name']`, it can replace with `Split<Paths<OBJECT>, '.'>`

And this is a broken change if replace type directly, so we should think about backward compatibility, example we can use `LiteralUnion<Paths<T>, string>` to replace `string` in `Get`

2023-11-07 11:07 UTC, Emiyaaaaa commented
>   Is result of `Paths` wrong?
>   or should add a option to choose the handling of array?

Should resolve this question in current PR, need your help~ @sindresorhus

2023-11-07 11:11 UTC, sindresorhus commented
I forgot that `Get` accepts `[0]`. Then it doesn't make sense to use `Paths`. We can consider adding an option for `Paths` to also generate `[0]` paths, but that shouldn't be part of this pull request and we should discuss it in an issue first.

2023-11-07 12:03 UTC, Emiyaaaaa commented
Changes: 
 - resolved review
 - add support for tuple with spread item
 - now will return `'0' | 0` for `Paths<[string]>`
 - now will return `never` for the type witch haven't any paths, like empty object and empty array.

2023-11-07 13:51 UTC, merged

2023-11-07 13:51 UTC, sindresorhus commented
Nice work 🎉

2023-11-08 03:58 UTC, Emiyaaaaa commented on source/paths.d.ts
> +							// If `Key` is a number, return `Key | `${Key}``, because both `array[0]` and `array['0']` do not work.
Is this a mistake? @sindresorhus

2023-11-08 08:24 UTC, sindresorhus commented on source/paths.d.ts
> +							// If `Key` is a number, return `Key | `${Key}``, because both `array[0]` and `array['0']` do not work.
Yes, fixed.