Add SingleKey and IfEmptyObject
sindresorhus/type-fest pull request #849
Opened 2024-03-30 07:28 UTC by ash-zzz

Closes #813 

I also added IfEmptyObject since that was a missing guard type that I needed to use for this

2024-03-30 17:08 UTC, sindresorhus commented
I think it should be named `SingleKeyObject`. The current name is a bit ambiguous and could make you single it fetches a single key from an object, for example.

2024-03-30 17:12 UTC, sindresorhus requested changes

2024-03-30 17:12 UTC, sindresorhus commented on source/single-key.d.ts
> +// 	IsUnion<keyof ObjectType> extends true ? never : {} extends ObjectType ? never : ObjectType;
Leftover

2024-03-30 17:12 UTC, sindresorhus commented on source/single-key.d.ts
> + */
```suggestion
*/
```

2024-03-30 17:12 UTC, sindresorhus commented on source/single-key.d.ts
> +// Compilation error
Document the actual compilation here.

2024-03-30 17:12 UTC, sindresorhus commented on source/single-key.d.ts
> +	},
Keep the example simple by not using a nested property here.

2024-03-30 21:47 UTC, ash-zzz commented on source/single-key.d.ts
> +// 	IsUnion<keyof ObjectType> extends true ? never : {} extends ObjectType ? never : ObjectType;
Oops I thought I removed them all

2024-03-30 21:49 UTC, ash-zzz commented
> I think it should be named `SingleKeyObject`. The current name is a bit ambiguous and could make you single it fetches a single key from an object, for example.

Agreed, I just renamed it and fixed the documentation

2024-03-31 05:57 UTC, merged

2024-03-31 05:57 UTC, sindresorhus commented
Thanks :)

2024-04-03 17:02 UTC, jakeboone02 commented
Thanks for doing this, @ash-zzz!

Should this work for types where the keys are unrestricted? If not, I'm not sure it satisfies my original request from #813, which was to declare an object type that requires exactly one key without restricting the key itself to any specific string or union of strings.

I tried `SingleKeyObject<Record<string, any>>` and `SingleKeyObject<{ [k: string]: any }>` but they both resolved to `never`. Something like `SingleKeyObject<Record<'union' | 'of' | 'strings', any>>` works fine.