`Integer` and `Float`: fix handing with edge case
sindresorhus/type-fest pull request #857
Opened 2024-04-07 07:39 UTC by Emiyaaaaa

fixed: #637 

Breaking but I think it's the corrent changes:
```ts
type Change1 = Integer<1 | 1.5>
// latest version => never // auther commented: This may be undesired behavior
// this PR        => 1

type Change2 = Integer<1e+100>
// latest version => never
// this PR        => 1e+100 // Number.IsInteger(1e+100) is true

type Change3 = Float<PositiveInfinity>
// latest version => PositiveInfinity
// this PR        => never // Infinity isn't a float.
```

And clarifies how to deal with some special number type like '1.0', '0x10' and negative number

2024-04-08 03:17 UTC, sindresorhus requested changes

2024-04-08 03:17 UTC, sindresorhus commented on source/numeric.d.ts
> +Returns the given number if it is a float, like `1.5` or `-1.5`.
It doesn't return the number.

```suggestion
Returns whether the given number is a float, like `1.5` or `-1.5`.
```

2024-04-08 03:17 UTC, sindresorhus commented on source/numeric.d.ts
> +Returns the given number if it is an integer, like `-5`, `1` or `100`.
```suggestion
Returns whether the given number is an integer, like `-5`, `1` or `100`.
```

2024-04-08 03:17 UTC, sindresorhus commented on source/numeric.d.ts
>  A `number` that is not an integer.
It should document the behavior for `Infinity`.

2024-04-08 03:17 UTC, sindresorhus commented on source/numeric.d.ts
> +Returns the given number if it is a float, like `1.5` or `-1.5`.
It should document the behavior for `Infinity`.

2024-04-09 03:36 UTC, Emiyaaaaa commented
Should we expose `IsFloat` and `IsInteger`? I think these are useful types. @sindresorhus

2024-04-09 04:35 UTC, sindresorhus commented
Yes. I think they are useful too. Up to you whether it's done now or in a later PR.

2024-04-22 08:22 UTC, merged