Add TypeName type #270
sindresorhus/type-fest pull request #935
Opened 2024-08-11 05:12 UTC by Max10240

fix #270

2024-08-11 12:33 UTC, sindresorhus requested changes

2024-08-11 12:33 UTC, sindresorhus commented on source/arrayable.d.ts
> +Create a type that represents either the value or array of the value.
```suggestion
Create a type that represents either the value or an array of the value.
```

2024-08-11 12:33 UTC, sindresorhus commented on source/arrayable.d.ts
> +  const outputList = Array.isArray(output) ? output : [output];
Tab-indentation

2024-08-11 12:33 UTC, sindresorhus commented on source/arrayable.d.ts
> +export type Arrayable<T> = T | T[];
```suggestion
export type Arrayable<T> = T | readonly T[];
```

2024-08-12 03:17 UTC, Emiyaaaaa approved these changes

2024-08-12 12:22 UTC, merged

2024-08-27 15:28 UTC, fregante commented
@sindresorhus why was `readonly []` chosen here? I'm unable to create a `castArray` function that is compatible with this.

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwIJSgQwJ5oEYBsCmAvnAGZQQhwDkMGY+AtCfgM4xUDcAUFyQK4A7AMYxgEAXCFo2KdBgCMAHgCSMfCAB8ACgBuaXH3wAuOLMw4CKtZoCUJ1eoDaAXURcAkFHww+UCWYwAOmAWAN19Qxs4AH44PQN8OBNHeMNnbkIefmFRcUlpGACAJit1bVTjU1RzPHxS2xMvNAATcVwMOAcQFzdPb19-aqCQsIqo2IqkuBSI-HSuTKA

2024-09-02 07:33 UTC, Max10240 commented
@fregante  `Item` cannot be an array type, because `Arrayable<unknown[]>` is equivalent to `unknown[] | readonly unknown[][]`, NOT `unknown[]` or `readonly unknown[]`. If `Item` is an Array type, `Array.isArray` will always return `true`, meaning that the actual return type of `castArray1 / castArray2` is actually `Item` itself, not `Item[]`.
I'm guessing what you're looking for is something like:
```tsx
import { Arrayable } from 'type-fest';

type Primitive =
	| bigint
	| boolean
	| null
	| number
	| string
	| symbol
	| undefined;

function castArray<Item extends Primitive | Record<PropertyKey, unknown>>(value: Arrayable<Item>): Item[] {
	return Array.isArray(value) ? value : [value];
}

```

2024-09-02 13:43 UTC, fregante commented
My previous code worked correctly if `readonly` is dropped, so that lengthy type information is a consequence of this keyword. 

You can see it working here: https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwIJSgQwJ5oEYBsCmAvnAGZQQhwDkMGY+AtCfgM4xUDcAUF7fXAAVcaYADsU6LHnwAeABoA+OAF44cuAB81AbQC63HiQCuogMYxgEUXFNo2EzAEYZASRj4QCgBQA3NLiN8AC5BYTEHKQJXd08AShC3Dz1ELgBIKHwYIyhrCIA6YBYI339A2LgAfjg-APw4EO0awP0uQkMTc0trW3tUTAAmaI9vJuC4CJwoxLiEmOSENIysnPG+jAKitZLa8qrR+rhG0vwWtqA