`Get`: Fix handling of paths with number template literal
sindresorhus/type-fest pull request #968
Opened 2024-10-19 06:30 UTC by sindresorhus

Fixes #967

2024-10-21 06:40 UTC, Emiyaaaaa requested changes

2024-10-21 06:40 UTC, Emiyaaaaa commented on test-d/get.ts
> +}
Add Test:
```
type FooPaths2 = `array.1`;
expectTypeOf<Get<Foo, FooPaths2>>().toEqualTypeOf<string | undefined>();
```

2024-10-21 07:42 UTC, sindresorhus commented on test-d/get.ts
> +}
Added

2024-11-06 15:45 UTC, merged

2024-11-07 12:50 UTC, Aliqag approved these changes

2024-11-12 01:16 UTC, Sexypella approved these changes

2024-11-13 22:26 UTC, KelvinNelly commented
https://github.com/KelvinNelly

2024-11-13 22:28 UTC, KelvinNelly commented
https://t.me/+DFz0KZdBu9U0NWM0
Join our telegram group.